# Generated by Django 6.0.2 on 2026-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
